[build]
  publish = "/"
  command = ""

[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Content-Encoding = "gzip"
    Cache-Control = "public,max-age=0,must-revalidate"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Content-Encoding = "gzip"
    Cache-Control = "public,max-age=0,must-revalidate"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"


[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200
  force = true
  trailing_slash = false

[[redirects]]
  from = "/apple-app-site-association"
  to = "/apple-app-site-association"
  status = 200
  force = true
  trailing_slash = false