[build]
  publish = "/"
  command = ""

[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Content-Encoding = "gzip"
    Cache-Control = "public,max-age=0"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Content-Encoding = "gzip"
    Cache-Control = "public,max-age=0"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/.well-known/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200
  force = true
  trailing_slash = false

[[redirects]]
  from = "/apple-app-site-association"
  to = "/apple-app-site-association"
  status = 200
  force = true
  trailing_slash = false

