[[headers]]
  for = "/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Content-Encoding = "gzip"
    Cache-Control = "public,max-age=0,must-revalidate"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Content-Encoding = "gzip"
    Cache-Control = "public,max-age=0,must-revalidate"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[build]
  publish = "build"

[redirects]
  trailing_slash = false